name: python312
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - akshare
  - ipykernel
  - exchange-calendars>=4.5.3     # May not be available at this version
  - numpy>=1.26.4                 # Version may not be available
  - pandas>=2.2.1                 # Version may not be available
  - python-dotenv>=1.0.1          # Version may not be available
  - sqlalchemy>=2.0.28            # Version may not be available
  - argparse>=1.4.0
  - psycopg2>=2.9.9               # Version may not be available
  - scikit-learn>=1.4.1           # Version may not be available
  - joblib>=1.3.2
  - yappi>=1.6.0
  - 'dask[complete]>=2024.4.1'    # Brackets need quotes; version may not be available
  - dask-expr
  - distributed
  - bokeh>=3.4.0
  - holidays>=0.47
  - arm-mango>=1.4.3
  - statsmodels>=0.14.2
  - utilsforecast
  - stock_indicators              # Requires manual installation of .NET SDK
  - mini-racer
  - lightning-fabric
  - pytorch-lightning
  - torch
  - py-cpuinfo
  # - pip:
    # The following packages require special handling:
    # - neuralprophet               # Needs installation from source
    # - neuralforecast            # Install from carusyte's repo
    # - ray>=2.33.0
