services:
  # grafana:
  #   image: grafana/grafana-enterprise
  #   # container_name: grafana
  #   restart: unless-stopped
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - grafana-storage:/var/lib/grafana
  #   networks:
  #     - pchn_network

  tsdb:
    image: timescale/timescaledb-ha:pg16.2-ts2.14.2-all
    container_name: tsdb
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - postgre_data:/home/postgres/pgdata/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      # create .env file with this variable in your local setup
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - POSTGRES_SHARED_PRELOAD_LIBRARIES=pg_stat_statements
    ##### enabling the 'pg_stat_statements' library may cause other (long) sql failing ####
    shm_size: '64gb'
    command: >
      postgres
      -c max_connections=1024
      -c shared_buffers=64GB
      -c work_mem=2GB
      -c maintenance_work_mem=2GB
      -c effective_cache_size=96GB
      -c max_parallel_workers=96
      -c max_parallel_maintenance_workers=96
      -c max_worker_processes=96
      -c max_parallel_workers_per_gather=96
      -c timescaledb.max_background_workers=96
      -c track_activity_query_size = 16384
    networks:
      - pchn_network

  # tdengine:
  #   image: tdengine/tdengine
  #   # container_name: tdengine
  #   restart: unless-stopped
  #   ports:
  #     - '6030-6041:6030-6041'
  #     - '6030-6041:6030-6041/udp'
  #   hostname: tdengine-server
  #   volumes:
  #     - tdengine_log:/var/log/taos
  #     - tdengine_data:/var/lib/taos
  #   networks:
  #     - pchn_network

volumes:
  # grafana-storage: {}
  postgre_data: {}
  # tdengine_log: {}
  # tdengine_data: {}

networks:
  pchn_network: {}
